services:
  rabbitmq:
    image: "rabbitmq:management-alpine"
    environment:
      - "RABBITMQ_DEFAULT_PASS=user"
      - "RABBITMQ_DEFAULT_USER=myuser"
    container_name: "rabbitmq-sb"
    ports:
      - "5672:5672"
      - "15672:15672"
